### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by 0xAWM** [zhouna/ml_python#2]
```
import matplotlib.pyplot as plt
import pandas as pd
from pandas import Series
import numpy as np
import math
```
better:

```
import math
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import Series
```

ref: https://www.python.org/dev/peps/pep-0008/#imports

**Comment by zhouna** [comment]
好的，多谢。
Style Guide for Python Guide
Imports
- import语句应该分开写，一行一个import
- imports 应该放在文件的顶部，在模块注释后面，模块globals和constants前面
  Imports should be grouped in the following order:
  1. standard library imports.
  2. Related third party imports.
  3. local application/library specific imports.
  每组引用之间用空行隔开

**Comment by lujqme** [comment]
你好，可以邮件联系我一下？ i@lujq.me
